# Generated by Django 4.1.7 on 2023-04-03 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_results_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Persons',
        ),
    ]
