# Generated by Django 4.1.7 on 2023-04-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_results_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='score',
            field=models.IntegerField(null=True, verbose_name='Общий балл'),
        ),
        migrations.AddField(
            model_name='persons',
            name='user_ie',
            field=models.IntegerField(null=True, verbose_name='user_ie'),
        ),
        migrations.AddField(
            model_name='persons',
            name='user_jp',
            field=models.IntegerField(null=True, verbose_name='user_ip'),
        ),
        migrations.AddField(
            model_name='persons',
            name='user_sn',
            field=models.IntegerField(null=True, verbose_name='user_sn'),
        ),
        migrations.AddField(
            model_name='persons',
            name='user_tf',
            field=models.IntegerField(null=True, verbose_name='user_tf'),
        ),
    ]
